---
-
  hosts: all
  gather_facts: true # this will make not to gather facts before running tasks

  tasks: 
    - name: Stop service on winrole or create new folder in webrole
      vars: ansible_env
    
    - include_tasks: >
            This is test if ansible
             {% if ansible_env.mainrole == 'win' -%}
                  winrole.yml
             {% elif ansible_env.subrole == 'web'-%}
                  webrole.yml
             {% else -%}
             This is not found
             {% endif %}
             
      
    


...

