---
-
  hosts: all
  gather_facts: true # this will make not to gather facts before running tasks

  tasks: 
   - name: tasks
     debug: 
       msg: this is main file
   
   - include_tasks: "{% if ansible_env.mainrole =='win'-%}winrole.yml{% endif %}"
             
      
    


...

