---
-
  hosts: all
  gather_facts: true # this will make not to gather facts before running tasks

  tasks: 
   - name: tasks
   
   - include_tasks: {% if ansible_env.mainrole == 'win' -%}winrole.yml{% elif ansible_env.subrole == 'web'-%}webrole.yml{% else -%}{% endif %}
             
      
    


...

